allowBuilds:
  '@heroui/shared-utils': false
  '@prisma/engines': set this to true or false
  '@tailwindcss/oxide': false
  esbuild: set this to true or false
  prisma: set this to true or false
  sharp: false
  unrs-resolver: false
